### ISSUE TITLE
Issue when importing torch from vs script

### ISSUE THREAD

**Issue by MonoS** [vapoursynth/vapoursynth#1024]
When importing VSGAN I receive an error regarding the loading of one of the dll, in particular cudnn_adv_infer64_8.dll , when importing it from the cmd everything works fine, i only have problem when using VS, for example i've created a simple .vpy script with only
`import torch`

When running it via `vspipe --info script.vpy` the loading stops at that dll, but when runnin it via `python script.vpy` everything works fine

The following output was generated by modifying pytorch's `__init__.py` to print the path of the dll it's trying to load (at row 123 of the source)
![image](https://github.com/vapoursynth/vapoursynth/assets/801011/24eb403e-bf27-4076-bf93-1c24966688f6)

```
vspipe --info "script.vpy"
C:\Program Files\Python311\Lib\site-packages\torch\lib\asmjit.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\c10.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\c10_cuda.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\caffe2_nvrtc.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cublas64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cublasLt64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudart64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll
Script evaluation failed:
Python exception: [WinError 127] Impossibile trovare la procedura specificata. Error loading "C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
  File "script.vpy", line 1, in <module>
    import torch
  File "C:\Program Files\Python311\Lib\site-packages\torch\__init__.py", line 131, in <module>
    raise err
OSError: [WinError 127] Impossibile trovare la procedura specificata. Error loading "C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.


python "script.vpy"
C:\Program Files\Python311\Lib\site-packages\torch\lib\asmjit.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\c10.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\c10_cuda.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\caffe2_nvrtc.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cublas64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cublasLt64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudart64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_adv_train64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_cnn_train64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_ops_infer64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cudnn_ops_train64_8.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cufft64_11.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cufftw64_11.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cupti64_2023.1.1.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\curand64_10.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cusolver64_11.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cusolverMg64_11.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\cusparse64_12.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\fbgemm.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\libiomp5md.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\libiompstubs5md.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\nvJitLink_120_0.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\nvrtc-builtins64_121.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\nvrtc64_120_0.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\nvToolsExt64_1.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\shm.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\torch.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\torch_cpu.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\torch_cuda.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\torch_global_deps.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\torch_python.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\uv.dll
C:\Program Files\Python311\Lib\site-packages\torch\lib\zlibwapi.dll
```

**Comment by HolyWu** [comment]
I guess you have `vstrt.dll` in your auto-loading plugins directory. The version of cuDNN got loaded by vstrt (in the `vsmlrt-cuda` directory) is not compatible with the one got loaded by PyTorch in its `lib` directory.

**Comment by MonoS** [comment]
Thanks @HolyWu that was exactly the case.
