### ISSUE TITLE
cannot import ccfDisableAutoLoading

### ISSUE THREAD

**Issue by joskezelensky** [vapoursynth/vapoursynth#1073]
how is this possible if i installed this correctly?
this is the stack trace
```
Failed to load %appdata%\VapourSynth\plugins64\DePan.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
C:\Program Files\Python312\Lib\site-packages\vspreview\main.py:854: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_distribution
C:\Program Files\Python312\Lib\site-packages\vspreview\main.py:869: DeprecationWarning: core.version_number() is deprecated, use core.core_version.release_major!
  if vs.core.version_number() < 53:
2024-06-18 15:32:46.190: DEBUG: Reading QSS file in: :qdarkstyle\dark\darkstyle.qss
2024-06-18 15:32:46.190: INFO: QSS file successfully loaded.
2024-06-18 15:32:46.190: DEBUG: Checking patches for being applied.
2024-06-18 15:32:46.190: INFO: Found version patches to be applied.
2024-06-18 15:32:46.190: INFO: Found application patches to be applied.
2024-06-18 15:32:46.999: ERROR: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth' (C:\Program Files\Python312\Lib\site-packages\vapoursynth.cp312-win_amd64.pyd)
Traceback (most recent call last):
  File "C:\Users\anton\Downloads\Encoding-Projects-master\Cowboy Bebop\Bebop.vpy", line 7, in <module>
    import lvsfunc as lvf
  File "%appdata%\Python\Python312\site-packages\lvsfunc\__init__.py", line 12, in <module>
    from . import (comparison, deblock, exceptions, export, grain, hdcam, misc,
  File "%appdata%\Python\Python312\site-packages\lvsfunc\comparison.py", line 9, in <module>
    from vskernels import Catrom, Kernel, KernelT, Point
  File "%appdata%\Python\Python312\site-packages\vskernels\__init__.py", line 1, in <module>
    from . import exceptions, kernels, util  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%appdata%\Python\Python312\site-packages\vskernels\exceptions.py", line 5, in <module>
    from vstools import CustomValueError, FuncExceptT
  File "%appdata%\Python\Python312\site-packages\vstools\__init__.py", line 5, in <module>
    from .utils import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "%appdata%\Python\Python312\site-packages\vstools\utils\__init__.py", line 1, in <module>
    from . import vs_proxy as vapoursynth
  File "%appdata%\Python\Python312\site-packages\vstools\utils\vs_proxy.py", line 17, in <module>
    from vapoursynth import (
ImportError: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth' (C:\Program Files\Python312\Lib\site-packages\vapoursynth.cp312-win_amd64.pyd)
```

**Comment by LightArrowsEXE** [comment]
This was an issue with vspreview, and has been fixed since. Update your vspreview.

**Comment by joskezelensky** [comment]
> This was an issue with vstools, and has been fixed since. Update your vstools and vspreview.

vspreview is really old, i don't think there will be any updates to it
do you mean that i update the deps that vspreview uses?

**Comment by LightArrowsEXE** [comment]
Yes, the JET version is the recommended version nowadays.

**Comment by joskezelensky** [comment]
> Yes, the JET version is the recommended version nowadays.

love it!
