### ISSUE TITLE
Python exception: lsmas: failed to construct index 

### ISSUE THREAD

**Issue by miraclemakerjoe** [vapoursynth/vapoursynth#1083]
import vapoursynth as vs
import awsmfunc as awf
import mvsfunc as mvf
import havsfunc as haf
from rekt import rektlvls
import kagefunc as kqf
import muvsfunc
core = vs.core

bd=core.lsmas.LWLibavSource(source="F:\The Color of Money 1986 BluRay 1080p AVC DTS-HD MA5.1-CHDBits\BDMV\STREAM\00800.m2ts")
web=core.lsmas.LWLibavSource(source="F:\The Color of Money 1986 1080p JPN Blu-ray AVC DTS-HD MA 5.1-bsj780\BDMV\STREAM\00800.m2ts")

bd= awf.FrameInfo(bd , 'BD') 
web= awf.FrameInfo(web , 'WEB')

bd .set_output(0)
web.set_output(9)

^^ It gave me errors:

"Failed to evaluate the script:
Python exception: lsmas: failed to construct index for F:\The Color of Money 1986 BluRay 1080p AVC DTS-HD MA5.1-CHDBits\BDMV\STREAM.

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate
File "", line 12, in 
File "src\cython\vapoursynth.pyx", line 2636, in vapoursynth.Function.__call__
vapoursynth.Error: lsmas: failed to construct index for F:\The Color of Money 1986 BluRay 1080p AVC DTS-HD MA5.1-CHDBits\BDMV\STREAM."

**Comment by Setsugennoao** [comment]
You just gotta escape the string with r""

**Comment by miraclemakerjoe** [comment]
> You just gotta escape the string with r""

import vapoursynth as vs
import awsmfunc as awf
import mvsfunc as mvf
import havsfunc as haf
from rekt import rektlvls
import kagefunc as kqf
import muvsfunc
core = vs.core


bd=core.lsmas.LWLibavSource(r"F:\The Color of Money 1986 BluRay 1080p AVC DTS-HD MA5.1-CHDBits\BDMV\STREAM\00800.m2ts")
web=core.lsmas.LWLibavSource(r"F:\The Color of Money 1986 1080p JPN Blu-ray AVC DTS-HD MA 5.1-bsj780\BDMV\STREAM\00800.m2ts")

bd= awf.FrameInfo(bd , 'BD') 
web= awf.FrameInfo(web , 'WEB')

bd .set_output(0)
web.set_output(9)




I changed to r"" still got the same error

**Comment by myrsloik** [comment]
No activity
