### ISSUE TITLE
VapourSynth doesn't work as intended on ARM64

### ISSUE THREAD

**Issue by aniotaweeb** [vapoursynth/vapoursynth#1096]
I've installed Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 10:17:29) [MSC v.1941 64 bit (ARM64)] on win32, but I keep encountering the following error during VapourSynth R70 installation via winget on my Dell Inspiron 14 Plus 7441 featuring a Snapdragon(R) X Elite - X1 E80100 - Qualcomm(R) Oryon(TM) CPU with ARM64 architecture. Strangely enough, I can install SVP, except motionflow interpolation doesn't work, consequently rendering it useless. Incidentally, I've installed VapourSynth and SVP on other machines featuring x86_64 CPUs with no issues. I'll attach the log here:

2024-11-27 20:49:52.361   Log opened. (Time zone: UTC-05:00)
2024-11-27 20:49:52.361   Setup version: Inno Setup version 6.3.3
2024-11-27 20:49:52.361   Original Setup EXE: C:\Users\User\AppData\Local\Temp\WinGet\VapourSynth.VapourSynth.R70\VapourSynth-x64-R70.exe
2024-11-27 20:49:52.361   Setup command line: /SL5="$2A0DF6,10954064,845824,C:\Users\User\AppData\Local\Temp\WinGet\VapourSynth.VapourSynth.R70\VapourSynth-x64-R70.exe" /LOG="C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-VapourSynth.VapourSynth.R70-2024-11-27-20-49-51.630.log" /CURRENTUSER
2024-11-27 20:49:52.365   Windows version: 10.0.26100
2024-11-27 20:49:52.365   Windows architecture: Arm64 (64-bit)
2024-11-27 20:49:52.365   Machine types supported by system: x86 x64 Arm64
2024-11-27 20:49:52.365   User privileges: Administrative
2024-11-27 20:49:52.369   Administrative install mode: No
2024-11-27 20:49:52.369   Install mode root key: HKEY_CURRENT_USER
2024-11-27 20:49:52.369   64-bit install mode: Yes
2024-11-27 20:49:52.371   Created protected temporary directory: C:\Users\User\AppData\Local\Temp\is-U55R5.tmp
2024-11-27 20:49:52.379   Message box (OK):
                          No suitable Python 3.12 or 3.8 64-bit installation found. The installer will now exit.
2024-11-27 20:49:54.712   User chose OK.
2024-11-27 20:49:54.715   InitializeSetup returned False; aborting.
2024-11-27 20:49:54.715   Got EAbort exception.
2024-11-27 20:49:54.715   Deinitializing Setup.
2024-11-27 20:49:54.719   Log closed.

Here's the output after running `pip install vapoursynth` in a terminal with PowerShell 7.4.6.0:

Collecting vapoursynth
  Using cached vapoursynth-70.zip (684 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 69, in <module>
        File "<string>", line 43, in query
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e67j8ka0\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e67j8ka0\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e67j8ka0\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e67j8ka0\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 72, in <module>
      OSError: Couldn't detect vapoursynth installation path
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by myrsloik** [comment]
You probably need to use a x64 python install to make this work. If it works at all. The installer doesn't have arm binaries.

**Comment by aniotaweeb** [comment]
After installing Python 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)] on win32, I installed the VapourSynth R70 binary successfully; however, mpv crashes when activating mvtools motionflow interpolation, and the console doesn't print an error message indicating why it crashed.

**Comment by aniotaweeb** [comment]
Copying the libfftw3-3, libfftw3f-3, and libmvtools Dynamic Link Library files from my old PC to my Dell Inspiron 14 Plus 7441's `%APPDATA%\Roaming\VapourSynth\plugins64` directory resolved this issue, since the binary package installer didn't write these DLLs to this directory during installation for some reason. Thank you for your help, @myrsloik!
