### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#274]
All Tests in `test/filter_test.py` fail.

```
Traceback (most recent call last):
  File "C:\Users\stux!\Desktop\vs2\vapoursynth\test\filter_test.py", line 36, in testLUT2_8Bit
    self.checkDifference(clipx, ret)
  File "C:\Users\stux!\Desktop\vs2\vapoursynth\test\filter_test.py", line 14, in checkDifference
    diff = self.core.std.PlaneDifference([cpu, gpu], 0, prop="PlaneDifference0")
  File "src\cython\vapoursynth.pyx", line 1430, in vapoursynth.Plugin.__getattr__ (src\cython\vapoursynth.c:28506)
AttributeError: There is no function named PlaneDifference
```

**Comment by myrsloik** [comment]
Fixed it
