### ISSUE TITLE
Able to create BlankClips with illegal formats

### ISSUE THREAD

**Issue by kageru** [vapoursynth/vapoursynth#338]
It is currently possible to register formats such as 32 bit integer and to create blank clips with them.
This means a user can create these clips (meaning they are allowed to exist in some way), but it's impossible to convert to or from these formats.
```
>>> int32 = core.register_format(vs.YUV, vs.INTEGER, 32, 0, 0)
>>> print(int32)
Format Descriptor
	Id: 3001002
	Name: YUV444P32
	Color Family: YUV
	Sample Type: Integer
	Bits Per Sample: 32
	Bytes Per Sample: 4
	Planes: 3
	Subsampling W: 0
	Subsampling H: 0
>>> blank = core.std.BlankClip(format=int32)
>>> blank.format.bits_per_sample
32
>>> blank.format.sample_type
<SampleType.INTEGER: 0>
>>> blank16 = core.std.BlankClip(format=vs.YUV444P16)
>>> # Convert to 32bit int
>>> blank16.resize.Point(format=int32)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 1722, in vapoursynth.Function.__call__ (src\cython\vapoursynth.c:35000)
vapoursynth.Error: Resize error: no matching pixel type for format: YUV444P32
>>> # Convert from 32bit int to a legal format
>>> blank.resize.Point(format=vs.YUV444P16)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 1722, in vapoursynth.Function.__call__ (src\cython\vapoursynth.c:35000)
vapoursynth.Error: Resize error: no matching pixel type for format: YUV444P32
```

**Comment by myrsloik** [comment]
It is a legal format. Integer allows everything between 8 and 32 bits. No conversion exists in the internal conversion library since it's a super rare case. Once you reach 32bits you should be using float anyway. At best it's a missing feature but one that you never should need...
