### ISSUE TITLE
No codec provided to avcodec_open2()

### ISSUE THREAD

**Issue by cronke99** [vapoursynth/vapoursynth#422]
Hello, I am testing Vapoursynth but having some problems. I figure to post here instead of d2vsource, I hope that is okay.

**Programs:**
```
Linux 4.18.0-0
Python 3.6
VS Core R45 built from latest git
Cython3 version 0.28.4
d2vsource built from latest git, built against ffmpeg below
x264 0.157.2935 545de2f
ffmpeg version N-47470-gfc94e9704e-static
```

**Script:**
```
import vapoursynth as vs
import functools
core = vs.get_core()
#commented out because softlink exists
#core.std.LoadPlugin(path=r'/usr/local/lib/libd2vsource.so')

video = core.d2v.Source('source.ts.d2v')
video = core.std.Trim(video, 0, 1000)

video.set_output()
```
---

Problem one, it did not recognize d2v option from d2vsource:
```
$ vspipe --y4m testing.vpy - | x264 --demuxer y4m - --output vs_test.mkv

Script evaluation failed:
Python exception: No attribute with the name d2v exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src/cython/vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "testing.vpy, line 6, in <module>
    video = core.d2v.Source('source.ts.d2v')
  File "src/cython/vapoursynth.pyx", line 1522, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name d2v exists. Did you mistype a plugin namespace?
```

So I made softlink to **/usr/local/lib/libd2vsource.so** inside **/usr/local/lib/vapoursynth**, and then I get this problem:
```
$ vspipe --y4m testing.vpy - | x264 --demuxer y4m - --output vs_test.mkv

[NULL @ 0x00000000] No codec provided to avcodec_open2()
Script evaluation failed:
Python exception: Cannot open decoder.

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src/cython/vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "testing.vpy", line 6, in <module>
    video = core.d2v.Source('source.ts.d2v')
  File "src/cython/vapoursynth.pyx", line 1833, in vapoursynth.Function.__call__
vapoursynth.Error: Cannot open decoder.

```
The same issue above happens even just checking the script with vspipe --info.
Source file is MPEG2 in .ts format. I wonder, what is it I am doing incorrect, or what is broken?
Greetings and thanks for guidance!

**Comment by cronke99** [comment]
The problem was I was using ffmpeg and libavcodec build from Debian repositories. I built from source, no problems. You can use none or whatever selected configure flags, it seems OK either way. Some flags I used which maybe are important: --non-free --enable-shared
