### ISSUE TITLE
Can't install VapourSynth with PIP

### ISSUE THREAD

**Issue by aaronfranke** [vapoursynth/vapoursynth#450]
Terminal output:

```
$ pip install VapourSynth
Collecting VapourSynth
  Downloading https://files.pythonhosted.org/packages/13/6a/990c6544e6fca02a917a045f8387bda500937dc7cdf2582b580499db3a4f/VapourSynth-45.tar.gz (378kB)
    100% |████████████████████████████████| 378kB 2.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SzBnRT/VapourSynth/setup.py", line 4, in <module>
        from shutil import which
    ImportError: cannot import name which
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SzBnRT/VapourSynth/
```

OS: Ubuntu 18.04 64-bit Linux

**Comment by stuxcrystal** [comment]
The pip version of Ubuntu 18.04 is installing pip for Python **2.7**. Use the package `python3-pip` and use the command `pip3 install VapourSynth`. Make sure that vapoursynth (the frame-server) itself has already been compiled and installed.

**Comment by stuxcrystal** [comment]
Did this fix your problem?
