### ISSUE TITLE
vspipe SIGSEGV from master version

### ISSUE THREAD

**Issue by Ilya87** [vapoursynth/vapoursynth#595]
My pc is Arch Linux x86_64 (Intrel Core i5 8600k) 16 Gb RAM.

gdb --args /usr/bin/vspipe bop.vpy 1.y4m --y4m

```
Thread 11 "vspipe" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2e48700 (LWP 95201)]
0x00007ffff51bdb2b in _mm_load_si128(long long __vector(2) const*) (__P=0x7fffe2e47998)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/emmintrin.h:697
697       return *__P;
(gdb) bt
#0  0x00007ffff51bdb2b in _mm_load_si128(long long __vector(2) const*) (__P=0x7fffe2e47998)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/emmintrin.h:697
#1  averageFramesByteSSE2 (d=0x555555df1020, srcs=0x7fffc8117960, dst=0x7fffc8302b70, plane=0, 
    vsapi=0x7ffff6fa2ae0 <vs_internal_vsapi>) at ../vapoursynth/src/filters/misc/miscfilters.cpp:256
#2  0x00007ffff51c0aad in averageFramesGetFrame (n=0, activationReason=2, instanceData=0x555555df16c0, frameData=0x7fffd0000c68, 
    frameCtx=0x7fffe2e47d70, core=0x55555575ed30, vsapi=0x7ffff6fa2ae0 <vs_internal_vsapi>)
    at ../vapoursynth/src/filters/misc/miscfilters.cpp:546
#3  0x00007ffff6d7d6d5 in VSNode::getFrameInternal (this=0x555555df16c0, n=0, activationReason=2, frameCtx=...)
    at ../vapoursynth/src/core/vscore.cpp:854
#4  0x00007ffff6db7822 in VSThreadPool::runTasks (owner=0x555555790660, stop=...) at ../vapoursynth/src/core/vsthreadpool.cpp:214
#5  0x00007ffff6dc0b79 in std::__invoke_impl<void, void (*)(VSThreadPool*, std::atomic<bool>&), VSThreadPool*, std::reference_wrapper<std::atomic<bool> > > (__f=@0x7fffd8000e28: 0x7ffff6db6f30 <VSThreadPool::runTasks(VSThreadPool*, std::atomic<bool>&)>)
    at /usr/include/c++/10.1.0/bits/invoke.h:60
#6  0x00007ffff6dc0a92 in std::__invoke<void (*)(VSThreadPool*, std::atomic<bool>&), VSThreadPool*, std::reference_wrapper<std::atomic<bool> > > (__fn=@0x7fffd8000e28: 0x7ffff6db6f30 <VSThreadPool::runTasks(VSThreadPool*, std::atomic<bool>&)>)
    at /usr/include/c++/10.1.0/bits/invoke.h:95
#7  0x00007ffff6dc09c3 in std::thread::_Invoker<std::tuple<void (*)(VSThreadPool*, std::atomic<bool>&), VSThreadPool*, std::reference_wrapper<std::atomic<bool> > > >::_M_invoke<0ul, 1ul, 2ul> (this=0x7fffd8000e18) at /usr/include/c++/10.1.0/thread:264
#8  0x00007ffff6dc0961 in std::thread::_Invoker<std::tuple<void (*)(VSThreadPool*, std::atomic<bool>&), VSThreadPool*, std::reference_wrapper<std::atomic<bool> > > >::operator() (this=0x7fffd8000e18) at /usr/include/c++/10.1.0/thread:271
#9  0x00007ffff6dc0945 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(VSThreadPool*, std::atomic<bool>&), VSThreadPool*, std::reference_wrapper<std::atomic<bool> > > > >::_M_run (this=0x7fffd8000e10) at /usr/include/c++/10.1.0/thread:215
#10 0x00007ffff7e7cb74 in std::execute_native_thread_routine (__p=0x7fffd8000e10)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#11 0x00007ffff76de422 in start_thread () from /usr/lib/libpthread.so.0
#12 0x00007ffff7ccbbf3 in clone () from /usr/lib/libc.so.6
```

**Comment by myrsloik** [comment]
Script?

**Comment by sekrit-twc** [comment]
Is it fixed in latest master?

**Comment by Ilya87** [comment]
```
import vapoursynth as vs
from havsfunc import MCTemporalDenoise
from havsfunc import LSFmod
file = r'video.mkv'
load = vs.core.ffms2.Source
clip = load(file)
clip = MCTemporalDenoise(clip, settings="low", edgeclean=True, ECrad=6, MVsharp=False)
clip = LSFmod(clip, defaults='slow', strength=200)
clip.set_output()
```

**Comment by Ilya87** [comment]
@sekrit-twc, fixed! Thank you!
