### ISSUE TITLE
Failed to initialize VapourSynth environment

### ISSUE THREAD

**Issue by ManoaNosea** [vapoursynth/vapoursynth#597]
```
ls /mnt/apps/python-3.8.3/lib/python3.8/site-packages
Cython                    easy_install.py       pkg_resources  README.txt                   vapoursynth.la
Cython-0.29.20.dist-info  pip                   __pycache__    setuptools                   vapoursynth.so
cython.py                 pip-20.1.1.dist-info  pyximport      setuptools-41.2.0.dist-info
```

```
PYTHONPATH=/mnt/apps/python-3.8.3/lib/python3.8/site-packages /mnt/apps/vapoursynth/bin/vspipe --version
Failed to initialize VapourSynth environment
```

I runned ldconfig and even tested LD_PRELOAD, didn't worked :x

**Comment by dubhater** [comment]
```
LD_LIBRARY_PATH=/mnt/apps/python-3.8.3/lib PYTHONPATH=/mnt/apps/python-3.8.3/lib/python3.8/site-packages /mnt/apps/vapoursynth/bin/vspipe --version
```

Does that work?

If you get a different error message, for example about libzimg.so, you have to add zimg's libdir to LD_LIBRARY_PATH, so it will probably look like this:
```
LD_LIBRARY_PATH=/mnt/apps/python-3.8.3/lib;/mnt/apps/zimg/lib PYTHONPATH=........
```

**Comment by ManoaNosea** [comment]
nope, didn't worked, same error, zimg is already in ld.so.conf and I also tested to make sure with the LD_LIBRARY_PATH.... somehow I don't think that library loading is the problem at all ...

**Comment by chriskretler** [comment]
@ManoaNosea I get the same thing when I don't have read perms on the the vapoursynth.so binary. It does appear that only read is needed:

`$ sudo chmod 711 /usr/local/lib/python3.6/site-packages/vapoursynth.so 
$ vspipe --version
Failed to initialize VapourSynth environment
$ sudo chmod 444 /usr/local/lib/python3.6/site-packages/vapoursynth.so 
$ vspipe --version
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R50
API R3.6
Options: -
`

Do you have read access on that file?

**Comment by dubhater** [comment]
strace could be useful:
```
PYTHONPATH=....... strace --output=strace.txt --trace=openat vspipe --version
```
See what it says in strace.txt. Maybe attach it here.

**Comment by ManoaNosea** [comment]
didn't worked ❌ 
```
ls -ashCl /mnt/apps/vapoursynth/lib/python3.8/site-packages/vapoursynth.*
4.0K -rwxrwxrwx 1 manoa manoa 1.3K Jun 22 02:06 /mnt/apps/vapoursynth/lib/python3.8/site-packages/vapoursynth.la
940K -rwxrwxrwx 1 manoa manoa 938K Jun 22 02:06 /mnt/apps/vapoursynth/lib/python3.8/site-packages/vapoursynth.so
```

```
openat(AT_FDCWD, "/mnt/apps/python-3.8.3/lib/python3.8/site-packages", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/mnt/apps/python-3.8.3/lib/python3.8", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/mnt/apps/python-3.8.3/lib/python3.8/encodings", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/mnt/apps/python-3.8.3/lib/python3.8/site-packages", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/mnt/apps/python-3.8.3/lib/python3.8/lib-dynload", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/mnt/apps/python-3.8.3/lib/python3.8/collections", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
+++ exited with 1 +++
```

**Comment by dubhater** [comment]
I guess that should have been without the ``--trace`` parameter after all. There may be more information in the parts it filtered out.

Another thing to try is ``import vapoursynth`` in the Python interpreter. If it fails, you may get an explanation there.

**Comment by ManoaNosea** [comment]
```
$ /mnt/apps/python-3.8.3/bin/python3.8
Python 3.8.3 (default, Jun 21 2020, 21:56:37)
[GCC 8.3.1 20191122] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cython/vapoursynth.pyx", line 28, in init vapoursynth
    import ctypes
  File "/mnt/apps/python-3.8.3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```
so what the problem ?

**Comment by dubhater** [comment]
Wonderful.
