### ISSUE TITLE
APIv4 changed Format.replace behaviour?

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vapoursynth#771]
Hello, why does this no longer work on the APIv4?
```py
import vapoursynth as vs
core = vs.core


clip = core.std.BlankClip(format=vs.YUV420P16)
assert clip.format
clip = clip.format.replace(color_family=vs.GRAY)
```

```
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2728, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2729, in vapoursynth._vpy_evaluate
  File "test1.py", line 7, in <module>
    clip = clip.format.replace(color_family=vs.GRAY)
  File "src\cython\vapoursynth.pyx", line 895, in vapoursynth.VideoFormat.replace
  File "src\cython\vapoursynth.pyx", line 2194, in vapoursynth.Core.query_video_format
vapoursynth.Error: Invalid format specified
```

**Comment by myrsloik** [comment]
The key here is that you try to get a subsampled GRAY format. You need to set subsampling to 0 in both directions and it'll work. I've now fixed it in the API3 branch so it'll be rejected everywhere. Previously you could create incompatible gray formats by doing this.

**Comment by Ichunjo** [comment]
Oh of course! Thank
