### ISSUE TITLE
R56 - AttributeError: There is no attribute or namespace named misc

### ISSUE THREAD

**Issue by aethanol** [vapoursynth/vapoursynth#798]
Recently attempting to update to the R56 vapoursynth and not able to use havsfunc now that misc is in its own package.
A command that errors: `filtered = haf.QTGMC(crop,TFF=True, FPSDivisor=2, Preset='Slow', TR2=1, SourceMatch=1)`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/havsfunc.py", line 1177, in QTGMC
    if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00
  File "/usr/lib/python3.9/site-packages/havsfunc.py", line 5318, in AverageFrames
    clip = SCDetect(clip, threshold=scenechange)
  File "/usr/lib/python3.9/site-packages/havsfunc.py", line 5633, in SCDetect
    sc = sc.misc.SCDetect(threshold=threshold)
  File "src/cython/vapoursynth.pyx", line 1695, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc
```

Am I just doing something wrong?
Compiled in a docker container with:
```
FROM archlinux:latest

RUN pacman -Syu --needed --noconfirm sudo
RUN useradd user --system --shell /bin/bash --create-home --home-dir /var/user
RUN passwd --lock user
RUN echo "user ALL=(ALL) NOPASSWD: /usr/bin/pacman" > /etc/sudoers.d/allow_user_to_pacman
RUN echo "root ALL=(ALL) CWD=* ALL" > /etc/sudoers.d/permissive_root_Chdir_Spec

RUN pacman -Syu --needed --noprogressbar --noconfirm base-devel git gcc ffms2 vapoursynth python-pip vim

USER user
WORKDIR /tmp
RUN git clone https://aur.archlinux.org/yay.git && \
    cd yay && \
    makepkg --noconfirm --noprogressbar -si && \
    yay --afterclean --removemake --save && cd -

# install vapoursynth plugins
RUN yay -Syu --overwrite "*" --noconfirm --noprogressbar --needed \
    vapoursynth-plugin-havsfunc-git \
    vapoursynth-plugin-awsmfunc-git \
    vapoursynth-plugin-continuityfixer-git

USER root

RUN pip install yuuno
RUN yuuno jupyter install
WORKDIR /
EXPOSE 7777
CMD ["jupyter", "notebook", "--allow-root", "--port=7777", "--no-browser", "--ip=0.0.0.0"]
```

**Comment by myrsloik** [comment]
You also need to install https://github.com/vapoursynth/vs-miscfilters-obsolete

**Comment by aethanol** [comment]
> You also need to install https://github.com/vapoursynth/vs-miscfilters-obsolete

Yeah, it is installed as a dependency of vapoursynth-plugin-havsfunc-git https://aur.archlinux.org/packages/vapoursynth-plugin-misc-git/
Though I just tried loading it manually and got an error: maybe this isn't compiling correctly
```
>>> from vapoursynth import core
>>> core.std.LoadPlugin("/usr/lib/vapoursynth/misc.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/cython/vapoursynth.pyx", line 2507, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load /usr/lib/vapoursynth/misc.so. Error given: /usr/lib/vapoursynth/misc.so: undefined symbol: _Znam
```

**Comment by myrsloik** [comment]
There shouldn't be any symbol reference called _Znam at all since it has zero library dependencies. Exactly how did you compile it?

**Comment by myrsloik** [comment]
That package is miscompiled. Doesn't properly link with c++ standard library. _Znam = new
Report to the maintainer. I've also removed the filtershared.h dependency from miscfilters now to make thing simpler.
