### ISSUE TITLE
Expr: expression compilation did not complete

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vapoursynth#847]
A somewhat basic expr doesn't work on R57 and master branch
```
>>> from vapoursynth import core
>>> core.std.Expr(
...     [core.std.BlankClip(),
...      core.std.BlankClip(),
...      core.std.BlankClip()],
...     'x x * z z * + x y * - y y * +'
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 2632, in vapoursynth.Function.__call__
vapoursynth.Error: Expr: expression compilation did not complete
```

**Comment by Setsugennoao** [comment]
I wonder why this works 🤔 
Is it a parsing error?

```
>>> core.std.Expr([
...     core.std.BlankClip(),
...     core.std.BlankClip(),
...     core.std.BlankClip()
... ], 'x y * -1 * x 2 pow z 2 pow y 2 pow + + +')
<vapoursynth.VideoNode object at 0x0000019341FECEC0>
```

**Comment by sekrit-twc** [comment]
````
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth as vs
>>> core = vs.core
>>> core.version()
'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: Extra Assertions\n'
>>> core.std.Expr([core.std.BlankClip(),core.std.BlankClip(),core.std.BlankClip()],'x x * z z * + x y * - y y * +')
<vapoursynth.VideoNode object at 0x000001991568BF40>
````

It also works in the debugger:

````
x x * z z * + x y * - y y * +
loadu8       r0,x
mul          r1,r0,r0
loadu8       r2,y
fma          r0,r1,r0,r2,2
loadu8       r1,z
fma          r0,r0,r1,r1,0
fma          r0,r0,r2,r2,0
storeu8      r0
````

**Comment by Setsugennoao** [comment]
doesn't work for me either
```
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth as vs
>>> core = vs.core
>>> core.version()
'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: -\n'
>>> core.std.Expr([core.std.BlankClip(),core.std.BlankClip(),core.std.BlankClip()],'x x * z z * + x y * - y y * +')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 2580, in vapoursynth.Function.__call__
vapoursynth.Error: Expr: expression compilation did not complete
>>>
```

**Comment by Ichunjo** [comment]
On my Ryzen 9 3900X and Ryzen 5 3600 it doesn't work. However, it works on my old i5 7400.

**Comment by Ichunjo** [comment]
WSL Ubuntu on Ryzen CPUs works too

**Comment by Setsugennoao** [comment]
I have a Ryzen 9 5900X btw ![](https://cdn.discordapp.com/emojis/767301135291252736.webp?size=16&quality=lossless)

**Comment by sekrit-twc** [comment]
For those experiencing errors, please run the expression through ExprDebugger (attached).
[ExprDebugger.zip](https://github.com/vapoursynth/vapoursynth/files/8004760/ExprDebugger.zip)

**Comment by Ichunjo** [comment]
```
ExprDebugger.exe "x x * z z * + x y * - y y * +"
x x * z z * + x y * - y y * +
loadu8       r0,x
mul          r1,r0,r0
loadu8       r2,y
fma          r0,r1,r0,r2,2
loadu8       r1,z
fma          r0,r0,r1,r1,0
fma          r0,r0,r2,r2,0
storeu8      r0
```
Same results than yours

**Comment by sekrit-twc** [comment]
What about this VS.dll (from master)?
[VapourSynth.zip](https://github.com/vapoursynth/vapoursynth/files/8004813/VapourSynth.zip)

**Comment by Ichunjo** [comment]
Same error

**Comment by sekrit-twc** [comment]
What about the debug build?
[VapourSynth.zip](https://github.com/vapoursynth/vapoursynth/files/8004919/VapourSynth.zip)

**Comment by Ichunjo** [comment]
I replaced the dll in `C:\Program Files\VapourSynth\core` and `C:\Program Files\Python39\Lib\site-packages` by the debug build but same error too on my Python 3.9 install.
On Python 3.10 it couldn't find the dll

**Comment by DJATOM** [comment]
Build from current master, 5950X.
![изображение](https://user-images.githubusercontent.com/4888694/152574246-40a0eb16-ae37-4f32-81ec-f01db52bc972.png)
