### ISSUE TITLE
VapourSynth fails to initialize on Fedora

### ISSUE THREAD

**Issue by ytsmaw** [vapoursynth/vapoursynth#910]
I can't run vspipe or run .vpy scripts from ffmpeg.
I installed vaporsynth via dnf on Fedora 36 and the packages I have installed are:
```
$ dnf list installed | grep vapoursynth
python3-vapoursynth.x86_64                           51-7.fc36                           @fedora                
vapoursynth-devel.x86_64                             51-7.fc36                           @fedora                
vapoursynth-libs.x86_64                              51-7.fc36                           @fedora                
vapoursynth-plugins.x86_64                           51-7.fc36                           @fedora                
vapoursynth-tools.x86_64                             51-7.fc36                           @fedora      
```
The error I get when I try to use vapoursynth with ffmpeg is:
```
$ ffmpeg -f vapoursynth -i 'deinterlace.vpy' out.mkv
  ffmpeg version N-109071-g92f9b28ed8 Copyright (c) 2000-2022 the FFmpeg developers
    built with gcc 12 (GCC)
    configuration: --prefix=/home/user/ffmpeg_build --pkg-config-flags=--static --extra-cflags='-I/home/user/ffmpeg_build/include -I/home/user/ffmpeg_build/include/decklink -I/usr/include/pulse' --extra-ldflags='-L/home/user/ffmpeg_build/lib -L/home/user/ffmpeg_build/include/decklink -L/usr/include/pulse' --extra-libs=-lpthread --extra-libs=-lm --bindir=/home/sleep/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libx264 --enable-nonfree --enable-libpulse --enable-vapoursynth --enable-decklink
    libavutil      57. 42.100 / 57. 42.100
    libavcodec     59. 52.101 / 59. 52.101
    libavformat    59. 34.101 / 59. 34.101
    libavdevice    59.  8.101 / 59.  8.101
    libavfilter     8. 50.100 /  8. 50.100
    libswscale      6.  8.112 /  6.  8.112
    libswresample   4.  9.100 /  4.  9.100
    libpostproc    56.  7.100 / 56.  7.100
  [vapoursynth @ 0x39ac4c0] Failed to initialize VSScript (possibly PYTHONPATH not set).
  deinterlace.vpy: Generic error in an external library
```
When I run vspipe -v I get:
```
$ vspipe -v
Failed to initialize VapourSynth environment
```
I have also tried running vspipe with the PYTHONPATH variable set:
```
$ PYTHONPATH=/home/user/.local/lib/python3.10/site-packages vspipe -v
Failed to initialize VapourSynth environment
```
When I import vapoursynth in Python, Python is able to find vapoursynth but runs into trouble when I try to get the version.
```
$ python
Python 3.10.8 (main, Oct 12 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth
>>> vapoursynth
<module 'vapoursynth' from '/home/user/.local/lib/python3.10/site-packages/vapoursynth.cpython-310-x86_64-linux-gnu.so'>
>>> vapoursynth.core.version()
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2364, in vapoursynth.vsscript_get_core_internal
  File "src\cython\vapoursynth.pyx", line 2342, in vapoursynth.createCore
vapoursynth.Error: Failed to obtain VapourSynth API pointer. System does not support SSE2 or is the Python module and loaded core library mismatched?
Exception ignored in: 'vapoursynth._set_logger'
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2364, in vapoursynth.vsscript_get_core_internal
  File "src\cython\vapoursynth.pyx", line 2342, in vapoursynth.createCore
vapoursynth.Error: Failed to obtain VapourSynth API pointer. System does not support SSE2 or is the Python module and loaded core library mismatched?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 2387, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 2374, in vapoursynth._CoreProxy.core.__get__
  File "src\cython\vapoursynth.pyx", line 2360, in vapoursynth._get_core
  File "src\cython\vapoursynth.pyx", line 2364, in vapoursynth.vsscript_get_core_internal
  File "src\cython\vapoursynth.pyx", line 2342, in vapoursynth.createCore
vapoursynth.Error: Failed to obtain VapourSynth API pointer. System does not support SSE2 or is the Python module and loaded core library mismatched?
```

**Comment by brucethemoose** [comment]
I dunno if you ever fixed this, but ` 51-7` seems like an old release?

**Comment by myrsloik** [comment]
Probably a user config issue and no updates
