### ISSUE TITLE
'PythonVSScriptLoggingBridge' object has no attribute 'parent'

### ISSUE THREAD

**Issue by brucethemoose** [vapoursynth/vapoursynth#926]
vspipe doesn't seem to like urllib3's logging. An error pops up when it tries to download/check model weights from the hub (which normally produces a progress bar graph and some notifications), while the same code runs fine in regular python.

I tested both the latest stable release and a git build of vapoursynth and this build of huggingface hub: https://pypi.org/project/huggingface-hub/0.12.0/

```
❯ vspipe -p -r 0 -s 2 -e 3 SDtest.vpy .
2023-01-26 16:50:14.208918: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Fetching 16 files:  19%|████████▊                                      | 3/16 [00:00<00:00, 60787.01it/s]
Script evaluation failed:
Python exception: 'PythonVSScriptLoggingBridge' object has no attribute 'parent'

Traceback (most recent call last):
  File "vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "SDtest.vpy", line 21, in <module>
    pipe = utils.images2img.StableDiffusionImages2ImgPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", revision="fp16", torch_dtype=torch.float16, safety_checker=None, requires_safety_checker=False)
  File "/home/alpha/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 524, in from_pretrained
    cached_folder = snapshot_download(
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 215, in snapshot_download
    thread_map(
  File "/usr/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/usr/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/usr/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 194, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1105, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1431, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 405, in _request_wrapper
    response = _request_wrapper(
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 440, in _request_wrapper
    return http_backoff(
  File "/home/alpha/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 129, in http_backoff
    response = requests.request(method=method, url=url, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/alpha/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/home/alpha/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/home/alpha/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1003, in _new_conn
    log.debug(
  File "/usr/lib/python3.10/logging/__init__.py", line 1465, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "vapoursynth.pyx", line 2910, in vapoursynth.PythonVSScriptLoggingBridge.emit
AttributeError: 'PythonVSScriptLoggingBridge' object has no attribute 'parent'
```

If the stack trace is not enough, I can run the python trace module or make a minimal vpy script/requirements.txt to reproduce it, just let me know.

**Comment by brucethemoose** [comment]
Oh nevermind, this was some other error from the hub that just wasnt being returned properly by vspipe.
