### ISSUE TITLE
v63 has not been published to pip repos

### ISSUE THREAD

**Issue by adworacz** [vapoursynth/vapoursynth#974]
Noticed this while working on some projects with requirements files stating ‘>=63’, which doesn’t currently exist. 

https://pypi.org/project/VapourSynth/

**Comment by Setsugennoao** [comment]
That is vapoursynth portable which isn't really an issue, it's mainly used for github workflows.

I already fixed the issue in the workflow that uploaded it, but now it'll be triggered on the next version release.

@cid-chan would have to manually upload it on PyPi.

**Comment by vludumu** [comment]
I went trough the same problem, without the pip version published, I can't install the last version of vs-preview (https://github.com/Irrational-Encoding-Wizardry/vs-preview). It is still looking for the pip version of vapoursynth63 even if vapoursynth63 is already installed.

**Comment by Setsugennoao** [comment]
if it's trying to install from pypi, you didn't install it correctly as it installs it for you https://github.com/vapoursynth/vapoursynth/blob/master/installer/vsinstaller.iss#L69

**Comment by adworacz** [comment]
>That is vapoursynth portable which isn't really an issue, it's mainly used for github workflows.

It's also used in virtualenvs, which myself (and I'm sure others) use to create stable encoding environments, particularly since so many plugins / scripts break between versions.

@cid-chan Would you mind manually uploading v63 to PyPi, per Setsu's comments above? It would be greatly appreciated.

**Comment by Setsugennoao** [comment]
As she hasn't got a Windows machine to compile on, gonna upload it here, compiled to a4d99c389821d287a215940a9d60ada013e44b81

(7z labeled as txt for GitHub)

[vapoursynth.pyd.7z.txt](https://github.com/vapoursynth/vapoursynth/files/11995515/vapoursynth.pyd.7z.txt)

**Comment by adworacz** [comment]
Ah thank you @Setsugennoao - I'm sure that will work for some Windows users. I'm personally on Linux. Perhaps I can follow a similar approach to compiling things myself to workaround this issue - where might I find how to do that?

**Comment by adworacz** [comment]
Never mind!

I answered my own question - when operating in a virtual env on Linux, you can install v63 easily using a simple:

```sh
pip install https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R63.tar.gz
```

**Comment by Setsugennoao** [comment]
Yeah, vapoursynth and vapoursynth-portable on pypi are windows only, linux users should always just compile it
There are no manylinux distributions

**Comment by HolyWu** [comment]
Actually I think http://www.vapoursynth.com/doc/installation.html#compilation should add a `pip3 install .` after `make install` so the Python package is also installed without needing to rely on package on PyPI.

**Comment by vludumu** [comment]
I didn't include the python integration as it wasn't specified in the doc.
With the R62 this wasn't a problem as I was installing it as a dependence of another pip installation.

**Comment by adworacz** [comment]
Strangely, I've seen Vapoursynth start failing to compile, even following the manual compilation instructions and `pip3 install .` like HolyWu calls out above.

Here's the logs of a more recent build on an up to date (as of today) Arch linux install in a virtual env running Python 3.11.3 as built by pyenv.

```
Processing /home/user/src/vapoursynth-playground/vapoursynth-10b5ead306682ebe232df895ef5c88ab279f7d87
  Preparing metadata (setup.py) ... done
Installing collected packages: VapourSynth
  DEPRECATION: VapourSynth is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for VapourSynth ... error
  error: subprocess-exited-with-error

  × Running setup.py install for VapourSynth did not run successfully.
  │ exit code: 1
  ╰─> [164 lines of output]
      /home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      running install
      /home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Compiling src/cython/vapoursynth.pyx because it changed.
      [1/1] Cythonizing src/cython/vapoursynth.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

              return env

          def set_logger(self, env, logger):
              Py_INCREF(logger)
              _set_logger(env, _logCb, _logFree, <void *>logger)
                               ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:256:25: Cannot assign type 'void (__stdcall )(int, const char *, void *) except * nogil' to 'VSLogHandler'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

              return env

          def set_logger(self, env, logger):
              Py_INCREF(logger)
              _set_logger(env, _logCb, _logFree, <void *>logger)
                                       ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:256:33: Cannot assign type 'void (__stdcall )(void *) except * nogil' to 'VSLogHandlerFree'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          if env is None:
              raise Error('Internal environment id not set. Did the environment die?')
          fdata = createFuncData(func, core, env)

          Py_INCREF(fdata)
          instance.ref = instance.funcs.createFunction(publicFunction, <void *>fdata, freeFunc, core)
                                                       ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:729:49: Cannot assign type 'void (__stdcall )(const VSMap *, VSMap *, void *, VSCore *, const VSAPI *) except * nogil' to 'VSPublicFunction'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          if env is None:
              raise Error('Internal environment id not set. Did the environment die?')
          fdata = createFuncData(func, core, env)

          Py_INCREF(fdata)
          instance.ref = instance.funcs.createFunction(publicFunction, <void *>fdata, freeFunc, core)
                                                                                      ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:729:80: Cannot assign type 'void (__stdcall )(void *) except * nogil' to 'VSFreeFunctionData'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  return _handle_future.fut

              cdef CallbackData data = createCallbackData(self.funcs, self, cb)
              Py_INCREF(data)
              with nogil:
                  self.funcs.getFrameAsync(n, self.node, frameDoneCallback, <void *>data)
                                                         ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:1808:51: Cannot assign type 'void (__stdcall )(void *, const VSFrame *, int, VSNode *, const char *) except * nogil' to 'VSFrameDoneCallback'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

          def add_log_handler(self, handler_func):
              handler_func(MESSAGE_TYPE_DEBUG, 'New message handler installed from python')
              cdef LogHandle lh = createLogHandle(handler_func)
              Py_INCREF(lh)
              lh.handle = self.funcs.addLogHandler(log_handler_wrapper, log_handler_free, <void *>lh, self.core)
                                                   ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:2528:45: Cannot assign type 'void (__stdcall )(int, const char *, void *) except * nogil' to 'VSLogHandler'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

          def add_log_handler(self, handler_func):
              handler_func(MESSAGE_TYPE_DEBUG, 'New message handler installed from python')
              cdef LogHandle lh = createLogHandle(handler_func)
              Py_INCREF(lh)
              lh.handle = self.funcs.addLogHandler(log_handler_wrapper, log_handler_free, <void *>lh, self.core)
                                                                        ^
      ------------------------------------------------------------

      src/cython/vapoursynth.pyx:2528:66: Cannot assign type 'void (__stdcall )(void *) except * nogil' to 'VSLogHandlerFree'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/user/src/vapoursynth-playground/vapoursynth-10b5ead306682ebe232df895ef5c88ab279f7d87/setup.py", line 90, in <module>
          setup(
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/user/src/vapoursynth-playground/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/user/src/vapoursynth-playground/vapoursynth-10b5ead306682ebe232df895ef5c88ab279f7d87/.eggs/Cython-3.0.0-py3.11-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/home/user/src/vapoursynth-playground/vapoursynth-10b5ead306682ebe232df895ef5c88ab279f7d87/.eggs/Cython-3.0.0-py3.11-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/home/user/src/vapoursynth-playground/vapoursynth-10b5ead306682ebe232df895ef5c88ab279f7d87/.eggs/Cython-3.0.0-py3.11-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/cython/vapoursynth.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> VapourSynth

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3.1 -> 23.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by HolyWu** [comment]
It seems that Cython 3.0 (released on Jul 17, 2023) has some backwards incompatible changes, hence the cython codes now fail to compile. In the meantime you need to install Cython 0.29.x (`pip install "Cython<3.0"`) until the cython codes have been adapted to Cython 3.0. @myrsloik

**Comment by adworacz** [comment]
I'm going ahead and resolving this, as all of the issues have been fixed upstream and a [workaround exists](https://github.com/vapoursynth/vapoursynth/issues/974#issuecomment-1631805092) for the current version.

Thanks for everyone's help on this.
