### ISSUE TITLE
Uncaught exception in std.FrameEval

### ISSUE THREAD

**Issue by sekrit-twc** [vapoursynth/vapoursynth#976]
````
import functools
import vapoursynth as vs

core = vs.core

clip = core.std.BlankClip()

def errar(n, clip):
    if n == 0:
        raise ValueError('oh noes')
    return clip

clip = core.std.FrameEval(clip, functools.partial(errar, clip=clip))
clip.set_output()
````

If running single-threaded, there is no issue:

````
$ vspipe -r 1 -p test.vpy .
Script evaluation done in 0.00 seconds
Error: Failed to retrieve frame 0 with error:
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2950, in vapoursynth.publicFunction
    with use_environment(d.env).use():
  File "src/cython/vapoursynth.pyx", line 2952, in vapoursynth.publicFunction
    ret = d(**m)
  File "src/cython/vapoursynth.pyx", line 680, in vapoursynth.FuncData.__call__
    return self.func(**kwargs)
  File "test.vpy", line 10, in errar
    raise ValueError('oh noes')
ValueError: oh noes

Output 1 frames in 0.00 seconds (1443.06 fps)
````

But if running multi-threaded:

````
$ vspipe -p test.vpy .
Script evaluation done in 0.00 seconds
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)

(gdb) bt
#6  0x00007f3ea8aa8e85 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f3ea8aa90d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f3ea8aa0240 in std::__throw_out_of_range(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f3ea769de1c in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, vs_intrusive_ptr<VSArrayBase>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vs_intrusive_ptr<VSArrayBase> > > >::at (__k="_Error", this=0x5590b2cc35c8) at /usr/include/c++/12/bits/stl_map.h:551
#10 VSMap::getErrorMessage (this=<optimized out>) at src/core/vscore.h:364
#11 mapGetError (map=<optimized out>) at src/core/vsapi.cpp:251
#12 0x00007f3ea7684f6f in frameEvalGetFrameNoProps (n=1, activationReason=<optimized out>, instanceData=0x5590b2cc3660, frameData=0x5590b2cc1230,
    frameCtx=0x5590b2cc0f90, core=<optimized out>, vsapi=0x7f3ea7792de0 <vs_internal_vsapi>) at src/core/simplefilters.cpp:1496
#13 0x00007f3ea76ba30f in VSNode::getFrameInternal (this=this@entry=0x5590b2cc36e0, n=1, activationReason=activationReason@entry=0,
    frameCtx=frameCtx@entry=0x5590b2cc0f90) at src/core/vscore.cpp:952
````

**Comment by Setsugennoao** [comment]
Huh, looks like this always was an issue, it's there even in R55 🤔
